language: python
sudo: false
cache:
  directories:
    - eggs
python:
  - 2.7.13
env:
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
before_install:
  - pip install -r requirements.txt
install:
  - sed -ie "s#test-5.1#test-$PLONE_VERSION#" buildout.cfg
  - buildout annotate
  - buildout
script:
  - bin/code-analysis
  - bin/coverage run bin/test
after_success:
  - bin/coveralls
notifications:
  email:
    - itconsense@gmail.com
