language: python
sudo: false
cache:
  directories:
    - eggs
python:
  - 2.7
before_install:
  - pip install --upgrade pip setuptools zc.buildout
install:
  - buildout annotate
  - buildout
script:
  - bin/code-analysis
  - bin/coverage run bin/test
after_success:
  - bin/coveralls
notifications:
  email:
    - itconsense@gmail.com
